version: '3.3'

services:
  postgres:
    container_name: postgres_ms
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_ms
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
    ports:
      - 5050:80

  # mysql:
  #   container_name: mysql_ms
  #   image: mysql:5
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_MYSQL_USER}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_PORT=${DB_MYSQL_PORT}
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   container_name: phpmyadmin_ms
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80

